### PR TITLE
Fix/2FA

### PR DESCRIPTION
**Pull request by AllanWang**

### CODE REVIEW

**Comment by AllanWang** [comment]
The last commit is to test if the google authenticator will be opened. I'm going to assume that when successful, it will trigger another link which frost should intercept, but logging in likely won't save after that. I'll worry about that later once I'm certain the parts before that actually work

**Comment by Zenexer** [comment]
I've gotten this far.  The U2F activity appears briefly, but quickly disappears.  I'm also not really sure what to do with the response.

``` kotlin
override fun shouldOverrideUrlLoading(view: WebView, request: WebResourceRequest): Boolean {
    if (request.url.scheme == "intent" || request.url.scheme == "android-app") {
        val intent = Intent.parseUri(request.url.toString(), 0)
        val activity = view.context as Activity
        
        activity.startActivityForResult(intent, 0)
        return true
    }
    return super.shouldOverrideUrlLoading(view, request)
}
```

I'm not sure what to do from here because I can't find any documentation or even code.  [This gist](https://gist.github.com/KenanSulayman/0aaebcd639f8b45a17c4) offers a decent summary of [this spec](https://fidoalliance.org/specs/fido-u2f-v1.1-id-20160915/fido-u2f-javascript-api-v1.1-id-20160915.pdf), which explains the web side of things.  I haven't done Android development in several years, so perhaps you can piece together the puzzle, or even just return true for the time being (which is fine--it let's me use a different 2FA method).

Here are the relevant logcat lines from the same page in Chrome, with sensitive info removed.  I left one base64 string that decodes to partial JSON (not sure why it's only partial), but I removed sensitive info from the decoded JSON.

```
08-05 02:18:19.756   897  1750 I ActivityManager: START u0 {act=com.google.android.apps.authenticator.AUTHENTICATE cat=[android.intent.category.BROWSABLE] cmp=com.google.android.apps.authenticator2/com.google.android.apps.authenticator.api.AuthenticateActivity (has extras)} from uid 10056
08-05 02:18:19.802 28738 28738 D IntentExtraParser: Interpreting request {"type":"u2f_sign_request","appId":"https://www.facebook.com/u2f/app_id/?uid=...&s=...","challenge":"...","registeredKeys":[{"version":"U2F_V2","keyHandle":"..."},{"version":"U2F_V2","keyHandle":"..."},{"version":"U2F_V2","keyHandle":"..."},{"version":"U2F_V2","keyHandle":"..."}],"timeoutSeconds":300,"requestId":1}
08-05 02:18:19.888   897   958 I ActivityManager: Displayed com.google.android.apps.authenticator2/com.google.android.apps.authenticator.api.AuthenticateActivity: +99ms
08-05 02:18:20.931   897  1490 I ActivityManager: START u0 {cmp=com.google.android.apps.authenticator2/com.google.android.apps.authenticator.api.NfcSecurityKeyActivity (has extras)} from uid 10188
08-05 02:18:21.050 28738 28738 D NfcSecurityKeyService: logUrl: null
08-05 02:18:21.115   897   958 I ActivityManager: Displayed com.google.android.apps.authenticator2/com.google.android.apps.authenticator.api.NfcSecurityKeyActivity: +164ms
```

Same thing repeated, but this time I completed the authentication process:

```
08-05 02:23:54.020   897  6940 I ActivityManager: START u0 {act=com.google.android.apps.authenticator.AUTHENTICATE cat=[android.intent.category.BROWSABLE] cmp=com.google.android.apps.authenticator2/com.google.android.apps.authenticator.api.AuthenticateActivity (has extras)} from uid 10056
08-05 02:23:54.053 28738 28738 D IntentExtraParser: Interpreting request {"type":"u2f_sign_request","appId":"https://www.facebook.com/u2f/app_id/?uid=...&s=...","challenge":"...","registeredKeys":[{"version":"U2F_V2","keyHandle":"..."},{"version":"U2F_V2","keyHandle":"..."},{"version":"U2F_V2","keyHandle":"..."},{"version":"U2F_V2","keyHandle":"..."}],"timeoutSeconds":300,"requestId":1}
08-05 02:23:54.126   897   958 I ActivityManager: Displayed com.google.android.apps.authenticator2/com.google.android.apps.authenticator.api.AuthenticateActivity: +85ms
08-05 02:23:54.526   897  2012 I ActivityManager: START u0 {cmp=com.google.android.apps.authenticator2/com.google.android.apps.authenticator.api.NfcSecurityKeyActivity (has extras)} from uid 10188
08-05 02:23:54.618 28738 28738 D NfcSecurityKeyService: logUrl: null
08-05 02:23:54.681   897   958 I ActivityManager: Displayed com.google.android.apps.authenticator2/com.google.android.apps.authenticator.api.NfcSecurityKeyActivity: +143ms
08-05 02:24:10.500  2345  2345 D NativeNfcTag: Connect to a tech with a different handle
08-05 02:24:10.785  2345 29699 D NativeNfcTag: Starting background presence check
08-05 02:24:10.864 28738 29701 D NfcSecurityKeyService: Tag discovered: com.google.android.libraries.fido.u2f.secureelement.nfc.Tag@cc7861e.
08-05 02:24:10.964 28738 29701 D NfcSecureElement: Connected in 79 ms. I/O timeout: 800 ms
08-05 02:24:10.965 28738 29701 D NfcSecureElement: APDU to security key (14 bytes): ...
08-05 02:24:10.979 28738 29701 D NfcSecureElement: APDU from security key (8 bytes): ..., RTT: 11 ms
08-05 02:24:10.980 28738 29701 D NfcSecurityKey: Got version U2F_V2
08-05 02:24:10.980 28738 29701 D NfcSecureElement: APDU to security key (135 bytes): ...
08-05 02:24:11.062 28738 29701 D NfcSecureElement: APDU from security key (2 bytes): 6A80, RTT: 80 ms
08-05 02:24:11.062 28738 29701 W SecureElementSecurityKey: Wrong data error at key handle 0
08-05 02:24:11.066 28738 29701 D NfcSecureElement: APDU to security key (135 bytes): ...
08-05 02:24:11.315 28738 29701 D NfcSecureElement: APDU from security key (77 bytes): ..., RTT: 244 ms
08-05 02:24:11.316 28738 29701 D SecureElementSecurityKey: Response data received: ....
08-05 02:24:11.323   660   660 E VibratorService: Setting amplitude  to: 3596
08-05 02:24:11.347 28738 29701 D NfcSecurityKeyService: Signature/enroll data received: ....
08-05 02:24:11.368 28738 28738 D com.google.android.apps.authenticator.api.SqliteKeyHandleCache: Failed to update, inserting into cache
08-05 02:24:11.424   897  1750 W ActivityManager: Failed createPendingResult: activity ActivityRecord{7fe7504 u0 com.google.android.apps.authenticator2/com.google.android.apps.authenticator.api.NfcSecurityKeyActivity t7761 f} is finishing
08-05 02:24:11.425 28738 28738 D NfcSecurityKeyService: logUrl: null
08-05 02:24:11.431   897  1750 W ActivityManager: Failed createPendingResult: activity ActivityRecord{7fe7504 u0 com.google.android.apps.authenticator2/com.google.android.apps.authenticator.api.NfcSecurityKeyActivity t7761 f} is finishing
08-05 02:24:11.470 28738 28738 D AuthenticateActivity: Returning from activity with result: {"type":"u2f_sign_response","requestId":1,"responseData":{"keyHandle":"...","clientData":"eyJ0eXAiOiJuYXZpZ2F0b3IuaWQuZ2V0QXNzZXJ0aW9uIiwiY2hhbGxlbmdlIjoiLi4uIiwib3JpZ2luIjoiaHR0cHM6XC9cL3RvdWNoLmZhY2Vib29rLmNvbSIsImNpZF9wdWJrZXkiOiJ1bmF2YWlsYWJsZQo=","signatureData":"..."}}
```

**Comment by AllanWang** [comment]
@Zenexer I'll add a commit to see if `startActivityForResult` is the solution

**Comment by AllanWang** [comment]
^ That's to remove observables. Hopefully nothing breaks

**Comment by AllanWang** [comment]
^ Once that builds, you can try it out. Set logging to at least debug and look for "Result found for..."
All important logs contain "Frost:" which you may filter with

**Comment by AllanWang** [comment]
Ok the intent thing doesn't work well given that I end up launching myself. That's likely why I had it set to filter our FACEBOOK_COM in the first place

**Comment by Zenexer** [comment]
The code I posted above worked fine, aside from the fact that I don't know how to finish it so I can actually do something with the result.  The activity disappears, but that's likely because I'm passing 0.

If you remove the intent launch and just return true, it at least lets people with U2F enabled get past login.

**Comment by AllanWang** [comment]
@Zenexer try the test release for the commit above once it builds and let me know how it goes

**Comment by Zenexer** [comment]
No luck; same error.

**Comment by AllanWang** [comment]
@Zenexer I don't really see how your attempt differs from mine other than you explicitly launching a request and me seeing if the request is possible. Is your authenticator still not opening? If that still doesn't work, I'd rather just return true for intents and not launch anything else as it doesn't make sense to do so. But that still isn't much of a fix. 

Are you also able to go back once the page blinks? 

If there's still a way of creating whatever 2FA you have, you can let me know and I can try to replicate it.

**Comment by Zenexer** [comment]
Yes, there's still a way to create it; it's their newest method, I believe.  It's called U2F.  You need a hardware device for it to work, such as a YubiKey.

I'll submit a pull request that lets me log in but doesn't attempt to launch the activity.

**Comment by AllanWang** [comment]
@Zenexer I see. You can feel free to checkout from this branch and submit a PR. I'm thinking that a basic way is that if "intent:" is in the Uri just return true. This client is specific to the login anyways.

**Pull request merged**
