### PR TITLE
Obfuscate window tags for JS injection

### LINKED ISSUE #1504: Facebook claims Frost is phishing and blocks FB account
**Describe the bug**
Facebook describes Frost as an phising app that looks like the real facebook and try to steal your account.

Due to this I have to reset my account with new password and prove it is me. This have happened two times.

I do not use other apps/facebook services so this must be the app who triggers the facebook account reset.

Is it possible to trick FB into thinking that the app is a regular mobile browser? Maybe with user agent?

**To Reproduce**
Steps to reproduce the behaviour:
Happens randomly. Two times within the last 5 days of use.
I have used the app for 6 months without any issues.

**Details (please provide at least the app version):**
 - App Version: 2.3.1
 - Device: Custom rom
 - Android Version: Android 8.1

---

Edit (Allan): 
Test build [v2519](https://github.com/AllanWang/Frost-for-Facebook-APK-Builder/releases/tag/v2519) and Release build [v2.3.2](https://github.com/AllanWang/Frost-for-Facebook/releases/tag/v2.3.2) are released with potential fixes

### PR DESCRIPTION
**Pull request by theopensourceguy**
An attempt to help debug/fix #1504. It might be the case that FB detects Frost manipulating the DOM by scanning for the tag that the app leaves in the window DOM object. To make this detection harder or maybe even impossible this patch obfuscates said tags, using the device ID as a reproducible seed for the RNG. 

Sadly, the device ID seems to be the only constant that doesn't require the device to be a phone or have Google Services/microG installed. If anyone has a better idea for an RNG seed I'm open to any and all suggestions.

Also, in order to obtain the device ID, I needed access to the application context. If there's a more elegant way to obtain it than to put a singleton companion object into the FrostApp class, please let me know.

### CODE REVIEW

**Comment by AllanWang** [comment]
I don't think we need secure random to the point where it's seeded by the device id, given that the values will be used per device only anyways. Perhaps you'd like to change the tag creator such that it doesn't depend on context at all, as I believe I have some non android unit tests for function outputs.

Otherwise, I'll be happy to merge it.

In the future I may only enable this on release builds, as having a readable tag does help with figuring out what is loaded when

**Comment by AllanWang** [comment]
To add onto this, I also have to look and see how the injectors are loaded. Most of them are from assets, where the injector should be created once, but otherwise this wouldn't work, as loading the same function twice would generate two tags due to randomness. To avoid unforseen problems, it's probably best that we just have a single hash function that guarantees matching inputs leads to matching output. It's fine if the hashing function itself is created randomly.

**Comment by theopensourceguy** [comment]
> Perhaps you'd like to change the tag creator such that it doesn't depend on context at all, as I believe I have some non android unit tests for function outputs.

Thing is, I'm not a 100% sure about the lifecycle of the app. I need a seed that is seemingly random across all devices, but at the same time probably needs to be identical across different sessions of Frost on the individual device, in order to avoid duplicate injections. Do you think, using the default seed (i.e. the current time) upon initialization of TagObfuscator will accomplish that?

Another possibility that comes to mind would be to create a unique ID upon first launching Frost and storing those in the settings, but that wouldn't rid me of the Context dependency, would it :/

**Comment by theopensourceguy** [comment]
> To add onto this, I also have to look and see how the injectors are loaded. Most of them are from assets, where the injector should be created once, but otherwise this wouldn't work, as loading the same function twice would generate two tags due to randomness. 

Excellent point and a total oversight on my part. I'll get to work on a proper hashing function posthaste.

**Comment by AllanWang** [comment]
Simplest solution is just to call hashCode(). If you really want something random, you can even just prepend some random constant that you will create once lazily. I don't think it will matter much after that

**Comment by theopensourceguy** [comment]
> Simplest solution is just to call hashCode(). If you really want something random, you can even just prepend some random constant that you will create once lazily. I don't think it will matter much after that

That's pretty much the plan. Also, bit of a noob question, but I haven't worked with GitHub extensively yet: should I add more commits to this PR or open a new one (since I'm basically rewriting all this)?

**Comment by AllanWang** [comment]
If you are rewriting you can make a new one. If you want to retain the comments with the PR you can add onto this. I'm assuming the changes are small so I'll probably squash this into one commit when merging anyways

**Comment by AllanWang** [comment]
FYI for availability, I'm usually free 10pm-12am PST, and maybe for a few minutes in the morning. I will likely review this PR in 20 hours

**Comment by adolfintel** [comment]
@theopensourceguy If you don't want to use the device ID, you can just generate a random string and store it in a file.

**Comment by theopensourceguy** [comment]
I decided to go with a rewrite and, to be a bit more consistent with the current developments, base it on the native-toggle branch. This is to be continued in #1513.

**Pull request closed without merging**
