### PR TITLE
Add Danish translation from Crowdin

### PR DESCRIPTION
**Pull request by mhtorp**

### CODE REVIEW

**Comment by AllanWang** [comment]
Hello,

these translations are already available in crowdin correct?

I was away on an internship for a while which is why there were no updates. I will be pulling changes by the weekend

**Comment by mhtorp** [comment]
Yes, they are straight from crowdin. I would just save you the hassle of moving it yourself.

**Comment by AllanWang** [comment]
Thanks. Things are done automatically in [this branch](https://github.com/AllanWang/Frost-for-Facebook/commits/l10n_dev), but I need to manually review everything to make sure it passes lint tests. Danish looks like it is 100% translated so once I approve it it will pass through. Thank you for your help!

Translations will be merged through https://github.com/AllanWang/Frost-for-Facebook/pull/1104

**Comment by mhtorp** [comment]
Sounds great. Thank you!

tor. 4. okt. 2018 21.34 skrev Allan Wang <notifications@github.com>:

**Comment by AllanWang** [comment]
You can follow the updates here: https://github.com/AllanWang/Frost-for-Facebook/pull/1125

**Pull request closed without merging**
